export const INSPIRATIONAL_PHRASES = [
  'Give it a try',
  'Go for it',
  'It’s worth a shot',
  'Don’t give up',
  'Stay strong',
  'Never give up',
  'Come on! You can do it!',
  'You are doing awesome!',
  'This is tough, but you’re tougher',
  'You’re making a big change!',
  'I’m so proud of you!',
  'I admire how strong you are!',
  'Believe in yourself',
  'Don’t be afraid to try',
];
